# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
          - "1.15.2-erlang-26.0.2-ubuntu-jammy-20230126"
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v3
      - name: ecto test under ${{ matrix.elixirbase }}
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{ matrix.elixirbase }} +test
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    strategy:
      fail-fast: false
      matrix:
        elixirbase:
          - "1.15.2-erlang-26.0.2-ubuntu-jammy-20230126"
    steps:
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v3
      - name: ecto lint under ${{ matrix.elixirbase }}
        run: earthly -P --ci --build-arg ELIXIR_BASE=${{ matrix.elixirbase }} +lint
      - name: Cache PLT files
        id: cache_plt
        uses: actions/cache@v3
        env:
          cache-name: cache_plt
        with:
          path: |
            /src/simple_xml/_build/test/*.plt
            /src/simple_xml/_build/test/*.plt.hash
          key: lint-${{ env.cache-name }}-base-${{ matrix.elixirbase }}
          restore-keys: |
            lint-${{ env.cache-name }}-base-${{ matrix.elixirbase }}
            lint-${{ env.cache-name }}-base-
            lint-${{ env.cache-name }}-